### ISSUE TITLE
Manual AIF

### ISSUE THREAD

**Issue by mwaqar99** [marcocastellaro/dsc-mri-toolbox#3]
Hi there,
Can you please provide some guidance as to how we can put in a manually defined AIF?
Thanks

**Comment by marcocastellaro** [comment]
Dear @mwaqar99 I just added an example [here]( https://github.com/marcocastellaro/dsc-mri-toolbox/blob/f8797081b90a43023441af6c019c4c50b51c2e5e/DSC_main_demo_external_aif.m). 
I have also included in the toolbox a fitted AIF to test the demo. Please let me know if you see any issues.
